/************************************************************************************************************
@author         Accenture : Luke Emberton
@date           09-Sep-2017
@description:   This is the constants class for all static strings used in this namespace
**************************************************************************************************************/
public class BlAp_Constants {
    
    //The prefix for this namespace
    public static string PREFIX = 'BlAp_';
    
    //Appended to the end of all trigger handler classes
    public static string  CONTRACTAPINAME                    = 'Contract__c';
    public static string  SUPRESSIONAPINAME                    = 'Suppression__c';

}