/************************************************************************************************************
@author         Accenture : Luke Emberton
@date           10-Sep-2017
@description:   This is the constants class for all static strings used in this namespace
**************************************************************************************************************/
public with sharing class CuAp_Constants {
	//The prefix for this namespace
    public static string PREFIX = 'CuAp_';
    
    //Appended to the end of all trigger handler classes
    public static string  LOCATIONAPINAME                   = 'Location__c';
    
}