/************************************************************************************************************
@author    		Accenture : Luke Emberton
@date      		26-Aug-2017
@description: 	This class is a special exception class to throw exceptions from the data access classes
**************************************************************************************************************/
public with sharing class GLAp_LightningDataAccessException extends Exception {
    
}